name: CI

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  build:
    uses: filhype-organization/universal-devops-action/.github/workflows/github-actions.yml@test
    with:
      enable_mkdocs_build: true
      mkdocs_requirements: 'mkdocs-material mkdocs-swagger-ui-tag'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}